version: "3.8"

services:
  api:
    build: .
    container_name: lafs-api
    ports:
      - "3000:3000"
    networks:
      - lafs-net
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - lafs-net

networks:
  lafs-net:
    driver: bridge
